name: reader_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  connectivity: ^0.4.9+2
  flutter_downloader: ^1.5.0
  path_provider: ^1.6.14
  permission_handler: ^5.0.1+1
  open_file: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter   

flutter_icons:
  android: true
  image_path: "lib/assets/uzlib_png.png"
  image_path_android: "lib/assets/uzlib_png.png"  

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/locale/